#!/bin/sh
# This is the post installation script for globaleaks
set -e

# Create globaleaks user and add the user to required groups
if ! id -u globaleaks >/dev/null 2>&1; then
  adduser --quiet \
          --system \
	  --group \
          --disabled-login \
          --disabled-password \
          --home /var/globaleaks \
          --shell /bin/false \
          globaleaks
fi

if [ ! -d "/var/globaleaks" ]; then
    mkdir -m 700 /var/globaleaks && chown globaleaks:globaleaks /var/globaleaks
fi

usermod -a -G debian-tor globaleaks

if which pycompile >/dev/null 2>&1; then
  pycompile -p globaleaks
fi

# Automatically added by dh_apparmor/3.0.4-2ubuntu2.1
if [ "$1" = "configure" ]; then
    APP_PROFILE="/etc/apparmor.d/usr.bin.globaleaks"
    if [ -f "$APP_PROFILE" ]; then
        # Add the local/ include
        LOCAL_APP_PROFILE="/etc/apparmor.d/local/usr.bin.globaleaks"

        test -e "$LOCAL_APP_PROFILE" || {
            mkdir -p `dirname "$LOCAL_APP_PROFILE"`
            install --mode 644 /dev/null "$LOCAL_APP_PROFILE"
        }

        # Reload the profile, including any abstraction updates
        if aa-enabled --quiet 2>/dev/null; then
            apparmor_parser -r -T -W "$APP_PROFILE" || true
        fi
    fi
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p globaleaks 
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p globaleaks  || true
fi

# End automatically added section
# Automatically added by dh_installinit/13.6ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/etc/init.d/globaleaks" ]; then
		update-rc.d globaleaks defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d globaleaks $_dh_action || exit 1
	fi
fi
# End automatically added section

