#!/bin/sh
set -e

remove() {
  rm -rf /var/run/globaleaks
}

purge() {
  echo "Forcefully purging all globaleaks data"
  rm -rf /var/globaleaks
}

case "$1" in
  "remove")
    remove
    break
    ;;
  "purge")
    remove
    purge
    break;
    ;;
esac

# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = "purge" ] ; then
	update-rc.d globaleaks remove >/dev/null
fi
# End automatically added section
# Automatically added by dh_apparmor/3.0.4-2ubuntu2.1
if [ "$1" = "purge" ] && ! [ -e "/etc/apparmor.d/usr.bin.globaleaks" ] ; then
    rm -f "/etc/apparmor.d/disable/usr.bin.globaleaks" || true
    rm -f "/etc/apparmor.d/force-complain/usr.bin.globaleaks" || true
    rm -f "/etc/apparmor.d/local/usr.bin.globaleaks" || true
    rm -f /var/cache/apparmor/*/"usr.bin.globaleaks" || true
    rmdir /etc/apparmor.d/disable 2>/dev/null || true
    rmdir /etc/apparmor.d/local   2>/dev/null || true
    rmdir /etc/apparmor.d         2>/dev/null || true
fi
# End automatically added section


exit 0
