#!/bin/sh
set -e

# Automatically added by dh_installinit/13.6ubuntu1
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/globaleaks" ] ; then
	invoke-rc.d globaleaks stop || exit 1
fi
# End automatically added section

# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p globaleaks 
else
	dpkg -L globaleaks | perl -ne 's,/([^/]*)\.py$,/__pycache__/\1.*, or next; unlink $_ or die $! foreach glob($_)'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section


if which pyclean >/dev/null 2>&1; then
  pyclean -p globaleaks
else
  dpkg -L globaleaks | grep \.py$ | while read file
  do
    rm -f "${file}"[co] >/dev/null
  done
fi
